### ISSUE TITLE
Create multiply() for Fraction.java

### ISSUE THREAD

**Issue by egraciani** [egraciani/IWVG.SwC.egraciani#1]
El objetivo es crear el método multiply() en la clase Fraction. Este método multiplica una fracción por otra que pasamos por parámetro. Para multiplicar dos fracciones, basta con multiplicar numeradores y denominadores (e.g. (1/5) x (3/4) = ((1x3)/(5x4)) = (3/20). Para más info, ver wiki.

**Comment by egraciani** [comment]
Crear branch issue#01 para esta mejora

**Comment by Webkova** [comment]
He comentado los métodos isPropia() y testDivide() porque no pasa el test.
Añadida funcionalidad y test ok.
