### ISSUE TITLE
Create divide() for Fraction.java

### ISSUE THREAD

**Issue by egraciani** [egraciani/IWVG.SwC.egraciani#2]
El objetivo es crear el método divide() en la clase Fraction. Este método divide una fracción entre otra que pasamos por parámetro. Para dividir dos fracciones, basta con multiplicar numerador del dividendo por denominador del divisor, y dividirlo entre el numerador del divisor por el denominador del dividendo (e.g. (1/5) / (3/4) = ((1x4)/(5x3)) = (4/15). Para más info, ver wiki.

**Comment by egraciani** [comment]
Resolver este issue en la rama nueva issue#02

**Comment by cijaraadrian** [comment]
Realizado el metodo, se ha cambiado el test, en el segundo assert se realizaba de nuevo la operacion division. lo que se ha hecho es modificarlo para que solo se realize la operacion 1 vez.
