### ISSUE TITLE
Create isPropia() for Fraction.java

### ISSUE THREAD

**Issue by egraciani** [egraciani/IWVG.SwC.egraciani#3]
El objetivo es crear el método isPropia() en la clase Fraction. Este método dice si una fracción es propia o no devolviendo un booleano. Una fracción es propia si el numerador es inferior al denominador (e.g. (1/5) es propia ). Para más info, ver wiki.

**Comment by egraciani** [comment]
Resolver en issue#03

**Comment by DavidBlasVazquez** [comment]
Subida y fusionada con develop.
Un saludo.
