### ISSUE TITLE
Create addToCoordinateX(int numberToAdd) for Point.java

### ISSUE THREAD

**Issue by egraciani** [egraciani/IWVG.SwC.egraciani#4]
El objetivo es crear el método addToCoordinateX(int numberToAdd) que incrementa la coordenada X de un punto con el valor pasado por parámetro. (e.g. dado el punto pt=(1,3) al llamar al metodo pt.addToCoordinateX(3) tendremos que pt=(4,3). Para más info ver wiki.

**Comment by egraciani** [comment]
Resolver en branch issue#04

**Comment by Webkova** [comment]
Implementada funcionalidad y modificado test para que se ejecutase correctamente.
