### ISSUE TITLE
Create convertToUpperCase()  for User.java

### ISSUE THREAD

**Issue by egraciani** [egraciani/IWVG.SwC.egraciani#5]
El objetivo es crear el método convertToUpperCase() que convierte el nombre del User a mayúsculas (e.g. si name="Juan" entonces al llamar a user.convertToUpperCase() tendremos que el name de user es "JUAN"). Para más info ver wiki.

**Comment by egraciani** [comment]
Resolver en issue#05

**Comment by cijaraadrian** [comment]
Creado codigo para el metodo, pasados los test.

**Comment by egraciani** [comment]
Hola Adrián,
He hecho un push de develop y el metodo convertToUpperCase() me aparece sin hacer. ¿Puedes revisarlo porfa?

**Comment by cijaraadrian** [comment]
Hola, 
Acabo de entrar en el repositorio, en github y desde la rama develop, consigo ver la funcion hecha, y subida en el repositorio como te digo.

Te pongo el enlace para que veas que esta subido correctamente.

https://github.com/egraciani/IWVG.SwC.egraciani/blob/develop/src/main/java/es/upm/miw/User.java
